#!/bin/sh /etc/rc.common

START=97
STOP=8
USE_PROCD=1

PROG="/etc/shpun/auto-update-loop.sh"

start_service() {
	[ -x "$PROG" ] || return 1

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 300
	procd_set_param nice 15
	procd_close_instance
}
