#!/bin/sh /etc/rc.common
START=95
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /etc/shpun/agent.sh
    procd_set_param respawn 5 10 0
    procd_close_instance
}
