#!/bin/sh /etc/rc.common

START=97
STOP=8
USE_PROCD=1

PROG="/etc/shpun/auto-update-loop.sh"

start_service() {
	# Avoid racing the updater that is currently replacing this package.
	[ "${SHPUN_MANAGED_UPDATE:-0}" = "1" ] && {
		logger -t shpun-update "managed package update: auto-update start deferred"
		return 0
	}

	[ -x "$PROG" ] || return 1

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 300
	procd_set_param nice 15
	procd_close_instance
}
